// AUTO-GENERATED by lib/build-travel-info.mjs — do not hand-edit.
// Sources: https://github.com/annexare/Countries (MIT, currency data) and
// https://github.com/benjiao/world-plugs (plug/voltage/frequency data, factual IEC
// standards data). Re-run the script to refresh.
//
// Coverage differs between the two sources (252 countries have currency data, 218 have
// plug data -- every plug-dataset country is also in the currency dataset, so this
// table has exactly 252 keys) -- a code present in only one source has empty
// plugTypes/voltages/frequencies arrays, or absent currency* fields. Consumers must
// degrade silently on missing data rather than rendering a blank/broken badge.

export interface CountryTravelInfo {
  currencyCode?: string;
  currencyName?: string;
  currencySymbol?: string;
  plugTypes: string[];
  voltages: string[];
  frequencies: string[];
}

export const TRAVEL_INFO: Record<string, CountryTravelInfo> = {
  "AC": {
    "currencyCode": "SHP",
    "currencyName": "St. Helena Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "AD": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AE": {
    "currencyCode": "AED",
    "currencyName": "United Arab Emirates Dirham",
    "currencySymbol": "AED",
    "plugTypes": [
      "C",
      "D",
      "G"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AF": {
    "currencyCode": "AFN",
    "currencyName": "Afghan Afghani",
    "currencySymbol": "؋",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AG": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "AI": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "AL": {
    "currencyCode": "ALL",
    "currencyName": "Albanian Lek",
    "currencySymbol": "ALL",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AM": {
    "currencyCode": "AMD",
    "currencyName": "Armenian Dram",
    "currencySymbol": "֏",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AO": {
    "currencyCode": "AOA",
    "currencyName": "Angolan Kwanza",
    "currencySymbol": "Kz",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AR": {
    "currencyCode": "ARS",
    "currencyName": "Argentine Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AS": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B",
      "F",
      "I"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "AT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AU": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "AW": {
    "currencyCode": "AWG",
    "currencyName": "Aruban Florin",
    "currencySymbol": "AWG",
    "plugTypes": [
      "A",
      "B",
      "F"
    ],
    "voltages": [
      "127 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "AX": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "AZ": {
    "currencyCode": "AZN",
    "currencyName": "Azerbaijani Manat",
    "currencySymbol": "₼",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BA": {
    "currencyCode": "BAM",
    "currencyName": "Bosnia-Herzegovina Convertible Mark",
    "currencySymbol": "KM",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BB": {
    "currencyCode": "BBD",
    "currencyName": "Barbadian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "115 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BD": {
    "currencyCode": "BDT",
    "currencyName": "Bangladeshi Taka",
    "currencySymbol": "৳",
    "plugTypes": [
      "C",
      "D",
      "G",
      "K"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BE": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BF": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BG": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BH": {
    "currencyCode": "BHD",
    "currencyName": "Bahraini Dinar",
    "currencySymbol": "BHD",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BI": {
    "currencyCode": "BIF",
    "currencyName": "Burundian Franc",
    "currencySymbol": "BIF",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BJ": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BL": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "BM": {
    "currencyCode": "BMD",
    "currencyName": "Bermudan Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "BN": {
    "currencyCode": "BND",
    "currencyName": "Brunei Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BO": {
    "currencyCode": "BOB",
    "currencyName": "Bolivian Boliviano",
    "currencySymbol": "Bs",
    "plugTypes": [
      "A",
      "C"
    ],
    "voltages": [
      "115 V",
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BQ": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "BR": {
    "currencyCode": "BRL",
    "currencyName": "Brazilian Real",
    "currencySymbol": "R$",
    "plugTypes": [
      "C",
      "N"
    ],
    "voltages": [
      "127 V",
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "BS": {
    "currencyCode": "BSD",
    "currencyName": "Bahamian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "BT": {
    "currencyCode": "BTN",
    "currencyName": "Bhutanese Ngultrum",
    "currencySymbol": "BTN",
    "plugTypes": [
      "C",
      "D",
      "F",
      "G",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BV": {
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "BW": {
    "currencyCode": "BWP",
    "currencyName": "Botswanan Pula",
    "currencySymbol": "P",
    "plugTypes": [
      "D",
      "G",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BY": {
    "currencyCode": "BYN",
    "currencyName": "Belarusian Ruble",
    "currencySymbol": "BYN",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "BZ": {
    "currencyCode": "BZD",
    "currencyName": "Belize Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B",
      "G"
    ],
    "voltages": [
      "110 V",
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "CA": {
    "currencyCode": "CAD",
    "currencyName": "Canadian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "CC": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "CD": {
    "currencyCode": "CDF",
    "currencyName": "Congolese Franc",
    "currencySymbol": "CDF",
    "plugTypes": [
      "C",
      "D",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CF": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CG": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CH": {
    "currencyCode": "CHF",
    "currencyName": "Swiss Franc",
    "currencySymbol": "CHF",
    "plugTypes": [
      "C",
      "J"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CI": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CK": {
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CL": {
    "currencyCode": "CLP",
    "currencyName": "Chilean Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "L"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CM": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CN": {
    "currencyCode": "CNY",
    "currencyName": "Chinese Yuan",
    "currencySymbol": "¥",
    "plugTypes": [
      "A",
      "C",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CO": {
    "currencyCode": "COP",
    "currencyName": "Colombian Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "CR": {
    "currencyCode": "CRC",
    "currencyName": "Costa Rican Colón",
    "currencySymbol": "₡",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "CU": {
    "currencyCode": "CUP",
    "currencyName": "Cuban Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "CV": {
    "currencyCode": "CVE",
    "currencyName": "Cape Verdean Escudo",
    "currencySymbol": "CVE",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CW": {
    "currencyCode": "XCG",
    "currencyName": "Caribbean guilder",
    "currencySymbol": "Cg",
    "plugTypes": [
      "A",
      "B",
      "C",
      "F"
    ],
    "voltages": [
      "127 V",
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CX": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "CY": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "CZ": {
    "currencyCode": "CZK",
    "currencyName": "Czech Koruna",
    "currencySymbol": "Kč",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "DE": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "DJ": {
    "currencyCode": "DJF",
    "currencyName": "Djiboutian Franc",
    "currencySymbol": "DJF",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "DK": {
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "E",
      "F",
      "K"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "DM": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "DO": {
    "currencyCode": "DOP",
    "currencyName": "Dominican Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "DZ": {
    "currencyCode": "DZD",
    "currencyName": "Algerian Dinar",
    "currencySymbol": "DZD",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "EC": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "EE": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "EG": {
    "currencyCode": "EGP",
    "currencyName": "Egyptian Pound",
    "currencySymbol": "E£",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "EH": {
    "currencyCode": "MAD",
    "currencyName": "Moroccan Dirham",
    "currencySymbol": "MAD",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "ER": {
    "currencyCode": "ERN",
    "currencyName": "Eritrean Nakfa",
    "currencySymbol": "ERN",
    "plugTypes": [
      "C",
      "L"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ES": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ET": {
    "currencyCode": "ETB",
    "currencyName": "Ethiopian Birr",
    "currencySymbol": "ETB",
    "plugTypes": [
      "C",
      "E",
      "F",
      "L"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "FI": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "FJ": {
    "currencyCode": "FJD",
    "currencyName": "Fijian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "FK": {
    "currencyCode": "FKP",
    "currencyName": "Falkland Islands Pound",
    "currencySymbol": "£",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "FM": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "FO": {
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "E",
      "F",
      "K"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "FR": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GA": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GB": {
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GD": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GE": {
    "currencyCode": "GEL",
    "currencyName": "Georgian Lari",
    "currencySymbol": "₾",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GF": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "D",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GG": {
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "GH": {
    "currencyCode": "GHS",
    "currencyName": "Ghanaian Cedi",
    "currencySymbol": "GH₵",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GI": {
    "currencyCode": "GIP",
    "currencyName": "Gibraltar Pound",
    "currencySymbol": "£",
    "plugTypes": [
      "C",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GL": {
    "currencyCode": "DKK",
    "currencyName": "Danish Krone",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "E",
      "F",
      "K"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GM": {
    "currencyCode": "GMD",
    "currencyName": "Gambian Dalasi",
    "currencySymbol": "GMD",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GN": {
    "currencyCode": "GNF",
    "currencyName": "Guinean Franc",
    "currencySymbol": "FG",
    "plugTypes": [
      "C",
      "F",
      "K"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GP": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "D",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GQ": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GR": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GS": {
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "GT": {
    "currencyCode": "GTQ",
    "currencyName": "Guatemalan Quetzal",
    "currencySymbol": "Q",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "GU": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "GW": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "GY": {
    "currencyCode": "GYD",
    "currencyName": "Guyanese Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B",
      "D",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "HK": {
    "currencyCode": "HKD",
    "currencyName": "Hong Kong Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "HM": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "HN": {
    "currencyCode": "HNL",
    "currencyName": "Honduran Lempira",
    "currencySymbol": "L",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "HR": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "HT": {
    "currencyCode": "HTG",
    "currencyName": "Haitian Gourde",
    "currencySymbol": "HTG",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "HU": {
    "currencyCode": "HUF",
    "currencyName": "Hungarian Forint",
    "currencySymbol": "Ft",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ID": {
    "currencyCode": "IDR",
    "currencyName": "Indonesian Rupiah",
    "currencySymbol": "Rp",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V 110 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IE": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IL": {
    "currencyCode": "ILS",
    "currencyName": "Israeli New Shekel",
    "currencySymbol": "₪",
    "plugTypes": [
      "C",
      "H",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IM": {
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "plugTypes": [
      "C",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IN": {
    "currencyCode": "INR",
    "currencyName": "Indian Rupee",
    "currencySymbol": "₹",
    "plugTypes": [
      "C",
      "D",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IO": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "IQ": {
    "currencyCode": "IQD",
    "currencyName": "Iraqi Dinar",
    "currencySymbol": "IQD",
    "plugTypes": [
      "C",
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IR": {
    "currencyCode": "IRR",
    "currencyName": "Iranian Rial",
    "currencySymbol": "IRR",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IS": {
    "currencyCode": "ISK",
    "currencyName": "Icelandic Króna",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "IT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F",
      "L"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "JE": {
    "currencyCode": "GBP",
    "currencyName": "British Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "JM": {
    "currencyCode": "JMD",
    "currencyName": "Jamaican Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "JO": {
    "currencyCode": "JOD",
    "currencyName": "Jordanian Dinar",
    "currencySymbol": "JOD",
    "plugTypes": [
      "B",
      "C",
      "D",
      "F",
      "G",
      "J"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "JP": {
    "currencyCode": "JPY",
    "currencyName": "Japanese Yen",
    "currencySymbol": "¥",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "100 V"
    ],
    "frequencies": [
      "50 Hz",
      "60 Hz"
    ]
  },
  "KE": {
    "currencyCode": "KES",
    "currencyName": "Kenyan Shilling",
    "currencySymbol": "KES",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KG": {
    "currencyCode": "KGS",
    "currencyName": "Kyrgyz Som",
    "currencySymbol": "⃀",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KH": {
    "currencyCode": "KHR",
    "currencyName": "Cambodian Riel",
    "currencySymbol": "៛",
    "plugTypes": [
      "A",
      "C",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KI": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KM": {
    "currencyCode": "KMF",
    "currencyName": "Comorian Franc",
    "currencySymbol": "CF",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KN": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B",
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "KP": {
    "currencyCode": "KPW",
    "currencyName": "North Korean Won",
    "currencySymbol": "₩",
    "plugTypes": [
      "A",
      "C",
      "F"
    ],
    "voltages": [
      "110 V",
      "220 V"
    ],
    "frequencies": [
      "50 Hz",
      "60 Hz"
    ]
  },
  "KR": {
    "currencyCode": "KRW",
    "currencyName": "South Korean Won",
    "currencySymbol": "₩",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "KW": {
    "currencyCode": "KWD",
    "currencyName": "Kuwaiti Dinar",
    "currencySymbol": "KWD",
    "plugTypes": [
      "C",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "KY": {
    "currencyCode": "KYD",
    "currencyName": "Cayman Islands Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "KZ": {
    "currencyCode": "KZT",
    "currencyName": "Kazakhstani Tenge",
    "currencySymbol": "₸",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LA": {
    "currencyCode": "LAK",
    "currencyName": "Laotian Kip",
    "currencySymbol": "₭",
    "plugTypes": [
      "A",
      "B",
      "C",
      "E",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LB": {
    "currencyCode": "LBP",
    "currencyName": "Lebanese Pound",
    "currencySymbol": "L£",
    "plugTypes": [
      "A",
      "B",
      "C",
      "D",
      "G"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LC": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LI": {
    "currencyCode": "CHF",
    "currencyName": "Swiss Franc",
    "currencySymbol": "CHF",
    "plugTypes": [
      "C",
      "J"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LK": {
    "currencyCode": "LKR",
    "currencyName": "Sri Lankan Rupee",
    "currencySymbol": "Rs",
    "plugTypes": [
      "D",
      "G",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LR": {
    "currencyCode": "LRD",
    "currencyName": "Liberian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B",
      "C",
      "E",
      "F"
    ],
    "voltages": [
      "120 V",
      "220 V"
    ],
    "frequencies": [
      "50 Hz",
      "60 Hz"
    ]
  },
  "LS": {
    "currencyCode": "LSL",
    "currencyName": "Lesotho Loti",
    "currencySymbol": "LSL",
    "plugTypes": [
      "M"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LU": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LV": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "LY": {
    "currencyCode": "LYD",
    "currencyName": "Libyan Dinar",
    "currencySymbol": "LYD",
    "plugTypes": [
      "C",
      "D",
      "F",
      "L"
    ],
    "voltages": [
      "127 V",
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MA": {
    "currencyCode": "MAD",
    "currencyName": "Moroccan Dirham",
    "currencySymbol": "MAD",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "127 V",
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MC": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "D",
      "E",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MD": {
    "currencyCode": "MDL",
    "currencyName": "Moldovan Leu",
    "currencySymbol": "MDL",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ME": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MF": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "120 V",
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "MG": {
    "currencyCode": "MGA",
    "currencyName": "Malagasy Ariary",
    "currencySymbol": "Ar",
    "plugTypes": [
      "C",
      "D",
      "E",
      "J",
      "K"
    ],
    "voltages": [
      "127 V",
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MH": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "MK": {
    "currencyCode": "MKD",
    "currencyName": "Macedonian Denar",
    "currencySymbol": "MKD",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ML": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MM": {
    "currencyCode": "MMK",
    "currencyName": "Myanmar Kyat",
    "currencySymbol": "K",
    "plugTypes": [
      "C",
      "D",
      "F",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MN": {
    "currencyCode": "MNT",
    "currencyName": "Mongolian Tugrik",
    "currencySymbol": "₮",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MO": {
    "currencyCode": "MOP",
    "currencyName": "Macanese Pataca",
    "currencySymbol": "MOP",
    "plugTypes": [
      "D",
      "F",
      "G",
      "M"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MP": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "MQ": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "D",
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MR": {
    "currencyCode": "MRU",
    "currencyName": "Mauritanian Ouguiya",
    "currencySymbol": "MRU",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MS": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "MT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MU": {
    "currencyCode": "MUR",
    "currencyName": "Mauritian Rupee",
    "currencySymbol": "Rs",
    "plugTypes": [
      "C",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MV": {
    "currencyCode": "MVR",
    "currencyName": "Maldivian Rufiyaa",
    "currencySymbol": "MVR",
    "plugTypes": [
      "A",
      "C",
      "D",
      "G",
      "J",
      "K",
      "L"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MW": {
    "currencyCode": "MWK",
    "currencyName": "Malawian Kwacha",
    "currencySymbol": "MWK",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MX": {
    "currencyCode": "MXN",
    "currencyName": "Mexican Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "127 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "MY": {
    "currencyCode": "MYR",
    "currencyName": "Malaysian Ringgit",
    "currencySymbol": "RM",
    "plugTypes": [
      "A",
      "C",
      "G",
      "M"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "MZ": {
    "currencyCode": "MZN",
    "currencyName": "Mozambican Metical",
    "currencySymbol": "MZN",
    "plugTypes": [
      "C",
      "F",
      "M"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NA": {
    "currencyCode": "NAD",
    "currencyName": "Namibian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "D",
      "M"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NC": {
    "currencyCode": "XPF",
    "currencyName": "CFP Franc",
    "currencySymbol": "CFPF",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NE": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NF": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "NG": {
    "currencyCode": "NGN",
    "currencyName": "Nigerian Naira",
    "currencySymbol": "₦",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NI": {
    "currencyCode": "NIO",
    "currencyName": "Nicaraguan Córdoba",
    "currencySymbol": "C$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "NL": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NO": {
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NP": {
    "currencyCode": "NPR",
    "currencyName": "Nepalese Rupee",
    "currencySymbol": "Rs",
    "plugTypes": [
      "C",
      "D",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NR": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "NU": {
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "NZ": {
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "OM": {
    "currencyCode": "OMR",
    "currencyName": "Omani Rial",
    "currencySymbol": "OMR",
    "plugTypes": [
      "C",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "PA": {
    "currencyCode": "PAB",
    "currencyName": "Panamanian Balboa",
    "currencySymbol": "PAB",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "PE": {
    "currencyCode": "PEN",
    "currencyName": "Peruvian Sol",
    "currencySymbol": "PEN",
    "plugTypes": [
      "A",
      "B",
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "PF": {
    "currencyCode": "XPF",
    "currencyName": "CFP Franc",
    "currencySymbol": "CFPF",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "PG": {
    "currencyCode": "PGK",
    "currencyName": "Papua New Guinean Kina",
    "currencySymbol": "PGK",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "PH": {
    "currencyCode": "PHP",
    "currencyName": "Philippine Peso",
    "currencySymbol": "₱",
    "plugTypes": [
      "A",
      "B",
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "PK": {
    "currencyCode": "PKR",
    "currencyName": "Pakistani Rupee",
    "currencySymbol": "Rs",
    "plugTypes": [
      "C",
      "D",
      "G",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "PL": {
    "currencyCode": "PLN",
    "currencyName": "Polish Zloty",
    "currencySymbol": "zł",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "PM": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "PN": {
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "PR": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "PS": {
    "currencyCode": "ILS",
    "currencyName": "Israeli New Shekel",
    "currencySymbol": "₪",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "PT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "PW": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "PY": {
    "currencyCode": "PYG",
    "currencyName": "Paraguayan Guarani",
    "currencySymbol": "₲",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "QA": {
    "currencyCode": "QAR",
    "currencyName": "Qatari Riyal",
    "currencySymbol": "QAR",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "RE": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "E"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "RO": {
    "currencyCode": "RON",
    "currencyName": "Romanian Leu",
    "currencySymbol": "lei",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "RS": {
    "currencyCode": "RSD",
    "currencyName": "Serbian Dinar",
    "currencySymbol": "RSD",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "RU": {
    "currencyCode": "RUB",
    "currencyName": "Russian Ruble",
    "currencySymbol": "₽",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "RW": {
    "currencyCode": "RWF",
    "currencyName": "Rwandan Franc",
    "currencySymbol": "RF",
    "plugTypes": [
      "C",
      "J"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SA": {
    "currencyCode": "SAR",
    "currencyName": "Saudi Riyal",
    "currencySymbol": "SAR",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "220 V",
      "230 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "SB": {
    "currencyCode": "SBD",
    "currencyName": "Solomon Islands Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "G",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SC": {
    "currencyCode": "SCR",
    "currencyName": "Seychellois Rupee",
    "currencySymbol": "SCR",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SD": {
    "currencyCode": "SDG",
    "currencyName": "Sudanese Pound",
    "currencySymbol": "SDG",
    "plugTypes": [
      "C",
      "D"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SE": {
    "currencyCode": "SEK",
    "currencyName": "Swedish Krona",
    "currencySymbol": "kr",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SG": {
    "currencyCode": "SGD",
    "currencyName": "Singapore Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "G",
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SH": {
    "currencyCode": "SHP",
    "currencyName": "St. Helena Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "SI": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SJ": {
    "currencyCode": "NOK",
    "currencyName": "Norwegian Krone",
    "currencySymbol": "kr",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "SK": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SL": {
    "currencyCode": "SLE",
    "currencyName": "Sierra Leonean Leone",
    "currencySymbol": "SLE",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SM": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [
      "C",
      "F",
      "L"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SN": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C",
      "D",
      "E",
      "K"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SO": {
    "currencyCode": "SOS",
    "currencyName": "Somali Shilling",
    "currencySymbol": "SOS",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SR": {
    "currencyCode": "SRD",
    "currencyName": "Surinamese Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "127 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "SS": {
    "currencyCode": "SSP",
    "currencyName": "South Sudanese Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "ST": {
    "currencyCode": "STN",
    "currencyName": "São Tomé & Príncipe Dobra",
    "currencySymbol": "Db",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SV": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "115 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "SX": {
    "currencyCode": "XCG",
    "currencyName": "Caribbean guilder",
    "currencySymbol": "Cg",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "SY": {
    "currencyCode": "SYP",
    "currencyName": "Syrian Pound",
    "currencySymbol": "£",
    "plugTypes": [
      "C",
      "E",
      "L"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "SZ": {
    "currencyCode": "SZL",
    "currencyName": "Swazi Lilangeni",
    "currencySymbol": "SZL",
    "plugTypes": [
      "M"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TA": {
    "currencyCode": "SHP",
    "currencyName": "St. Helena Pound",
    "currencySymbol": "£",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "TC": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "TD": {
    "currencyCode": "XAF",
    "currencyName": "Central African CFA Franc",
    "currencySymbol": "FCFA",
    "plugTypes": [
      "C",
      "D",
      "E",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TF": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "TG": {
    "currencyCode": "XOF",
    "currencyName": "West African CFA Franc",
    "currencySymbol": "F CFA",
    "plugTypes": [
      "C"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TH": {
    "currencyCode": "THB",
    "currencyName": "Thai Baht",
    "currencySymbol": "฿",
    "plugTypes": [
      "A",
      "B",
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TJ": {
    "currencyCode": "TJS",
    "currencyName": "Tajikistani Somoni",
    "currencySymbol": "TJS",
    "plugTypes": [
      "C",
      "F",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TK": {
    "currencyCode": "NZD",
    "currencyName": "New Zealand Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "TL": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "E",
      "F",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TM": {
    "currencyCode": "TMT",
    "currencyName": "Turkmenistani Manat",
    "currencySymbol": "TMT",
    "plugTypes": [
      "B",
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TN": {
    "currencyCode": "TND",
    "currencyName": "Tunisian Dinar",
    "currencySymbol": "TND",
    "plugTypes": [
      "C",
      "E"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TO": {
    "currencyCode": "TOP",
    "currencyName": "Tongan Paʻanga",
    "currencySymbol": "T$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TR": {
    "currencyCode": "TRY",
    "currencyName": "Turkish Lira",
    "currencySymbol": "₺",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TT": {
    "currencyCode": "TTD",
    "currencyName": "Trinidad & Tobago Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "115 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "TV": {
    "currencyCode": "AUD",
    "currencyName": "Australian Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "TW": {
    "currencyCode": "TWD",
    "currencyName": "New Taiwan Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "TZ": {
    "currencyCode": "TZS",
    "currencyName": "Tanzanian Shilling",
    "currencySymbol": "TZS",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "UA": {
    "currencyCode": "UAH",
    "currencyName": "Ukrainian Hryvnia",
    "currencySymbol": "₴",
    "plugTypes": [
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "UG": {
    "currencyCode": "UGX",
    "currencyName": "Ugandan Shilling",
    "currencySymbol": "UGX",
    "plugTypes": [
      "G"
    ],
    "voltages": [
      "240 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "UM": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "US": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "UY": {
    "currencyCode": "UYU",
    "currencyName": "Uruguayan Peso",
    "currencySymbol": "$",
    "plugTypes": [
      "C",
      "F",
      "I",
      "L"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "UZ": {
    "currencyCode": "UZS",
    "currencyName": "Uzbekistani Som",
    "currencySymbol": "UZS",
    "plugTypes": [
      "C",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "VA": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "VC": {
    "currencyCode": "XCD",
    "currencyName": "East Caribbean Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "C",
      "E",
      "G",
      "I",
      "K"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "VE": {
    "currencyCode": "VES",
    "currencyName": "Venezuelan Bolívar",
    "currencySymbol": "VES",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "120 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "VG": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "VI": {
    "currencyCode": "USD",
    "currencyName": "US Dollar",
    "currencySymbol": "$",
    "plugTypes": [
      "A",
      "B"
    ],
    "voltages": [
      "110 V"
    ],
    "frequencies": [
      "60 Hz"
    ]
  },
  "VN": {
    "currencyCode": "VND",
    "currencyName": "Vietnamese Dong",
    "currencySymbol": "₫",
    "plugTypes": [
      "A",
      "C",
      "F"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "VU": {
    "currencyCode": "VUV",
    "currencyName": "Vanuatu Vatu",
    "currencySymbol": "VUV",
    "plugTypes": [
      "C",
      "G",
      "I"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "WF": {
    "currencyCode": "XPF",
    "currencyName": "CFP Franc",
    "currencySymbol": "CFPF",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "WS": {
    "currencyCode": "WST",
    "currencyName": "Samoan Tala",
    "currencySymbol": "WST",
    "plugTypes": [
      "I"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "XK": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "YE": {
    "currencyCode": "YER",
    "currencyName": "Yemeni Rial",
    "currencySymbol": "YER",
    "plugTypes": [
      "A",
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "YT": {
    "currencyCode": "EUR",
    "currencyName": "Euro",
    "currencySymbol": "€",
    "plugTypes": [],
    "voltages": [],
    "frequencies": []
  },
  "ZA": {
    "currencyCode": "ZAR",
    "currencyName": "South African Rand",
    "currencySymbol": "R",
    "plugTypes": [
      "C",
      "D",
      "M",
      "N"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ZM": {
    "currencyCode": "ZMW",
    "currencyName": "Zambian Kwacha",
    "currencySymbol": "ZK",
    "plugTypes": [
      "C",
      "D",
      "G"
    ],
    "voltages": [
      "230 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  },
  "ZW": {
    "currencyCode": "ZWG",
    "currencyName": "Zimbabwean Gold",
    "currencySymbol": "ZWG",
    "plugTypes": [
      "D",
      "G"
    ],
    "voltages": [
      "220 V"
    ],
    "frequencies": [
      "50 Hz"
    ]
  }
};
